spin_manifest_version = 2

[application]
name = "boris-fiona-walker"
version = "0.1.0"
authors = ["Kingdon Barrett <kingdon@urmanac.com>"]
description = "WASM walk reminder system for Boris and Fiona"

[variables]
twilio_account_sid = { required = true }
twilio_auth_token = { required = true }
twilio_from_number = { required = true }
twilio_to_number = { required = true }
openweather_api_key = { required = true }
webhook_secret = { required = true }

[[trigger.http]]
route = "/check"
component = "walk-reminder"

[[trigger.http]]
route = "/..."
component = "walk-reminder"

[component.walk-reminder]
source = "target/wasm32-wasip1/release/boris_fiona_walker.wasm"
allowed_outbound_hosts = ["https://api.twilio.com", "https://api.openweathermap.org"]

[component.walk-reminder.build]
command = "cargo build --target wasm32-wasip1 --release"
watch = ["src/**/*.rs", "Cargo.toml"]

[component.walk-reminder.variables]
twilio_account_sid = "{{ twilio_account_sid }}"
twilio_auth_token = "{{ twilio_auth_token }}"  
twilio_from_number = "{{ twilio_from_number }}"
twilio_to_number = "{{ twilio_to_number }}"
webhook_secret = "{{ webhook_secret }}"
openweather_api_key = "{{ openweather_api_key }}"