name: Boris & Fiona Walk Reminder

on:
  schedule:
    # Run every hour from 2 PM to 6 PM Eastern (6 PM to 10 PM UTC)
    - cron: '0 18,19,20,21,22 * * *'
  workflow_dispatch: # Allow manual triggering for testing

jobs:
  trigger-walk-check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger Walk Reminder Check
        run: |
          echo "Checking if Boris and Fiona need their walk..."
          
          # Call the Spin Cloud WASM endpoint
          # TODO: Replace with actual Spin Cloud app URL after deployment
          # Expected format: https://boris-fiona-walker-xxx.fermyon.app/check
          response=$(curl -s -w "\n%{http_code}" \
            -X POST \
            -H "Content-Type: application/json" \
            "${{ secrets.SPIN_APP_URL }}/check" || echo "000")
          
          http_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | head -n -1)
          
          echo "Response Code: $http_code"
          echo "Response Body: $body"
          
          if [ "$http_code" -eq 200 ]; then
            echo "✅ Walk check completed successfully"
            
            # Parse JSON response to see if reminder was sent
            reminded=$(echo "$body" | jq -r '.reminded // false')
            if [ "$reminded" = "true" ]; then
              echo "🐕 Walk reminder sent to Kingdon for Boris and Fiona!"
            else
              echo "ℹ️ No reminder needed at this time"
            fi
          else
            echo "❌ Walk check failed with code $http_code"
            echo "Response: $body"
            exit 1
          fi

      - name: Report Status
        if: always()
        run: |
          echo "Walk reminder check completed at $(date)"
          echo "Next check in 1 hour (if within 2-6 PM Eastern window)"