"""
Post-Mortem Generator — Ghost Archivist self-healing module.

Queries the ``autonomous_turns`` table for failed sessions (exit_code != 0)
and drafts structured post-mortem markdown files in ``attic/post-mortems/``.

Plan: yebyen/mecris#255 / kingdonb/mecris#216
"""
import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, Optional

from services.token_bank import TokenBankService

logger = logging.getLogger("mecris.ghost.post_mortem")

DEFAULT_OUTPUT_DIR = Path("attic/post-mortems")


class PostMortemGenerator:
    """
    Generates post-mortem markdown files for failed autonomous turns.

    Uses ``TokenBankService.get_failed_turns()`` to retrieve failed sessions,
    then drafts structured reports in ``attic/post-mortems/``.

    Fail-open: if no DB URL is configured, ``run()`` returns None without error.
    """

    def __init__(
        self,
        db_url: Optional[str] = None,
        output_dir: Optional[Path] = None,
    ):
        self.bank = TokenBankService(db_url=db_url)
        self.output_dir = output_dir or DEFAULT_OUTPUT_DIR

    def run(self, user_id: str, limit: int = 1) -> Optional[Path]:
        """
        Check for failed turns and draft a post-mortem if any are found.

        Returns the path to the generated file, or None if no failures found.
        ``limit`` controls how many failed turns to query; only the most
        recent is used for the report.
        """
        failed = self.bank.get_failed_turns(user_id, limit=limit)
        if not failed:
            logger.info("PostMortem: No failed turns for %s. Nothing to report.", user_id)
            return None

        # get_failed_turns returns ORDER BY start_time DESC — first is most recent
        turn = failed[0]
        return self._draft_report(turn)

    def _draft_report(self, turn: Dict) -> Path:
        """Write the post-mortem markdown file and return its path."""
        ts: datetime = turn.get("start_time") or datetime.now(timezone.utc)
        if ts.tzinfo is None:
            ts = ts.replace(tzinfo=timezone.utc)

        date_str = ts.strftime("%Y-%m-%d")
        turn_id = turn.get("turn_id", "unknown")
        filename = f"{date_str}-failure-turn{turn_id}.md"
        output_path = self.output_dir / filename

        content = self._render_report(turn, date_str)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        output_path.write_text(content, encoding="utf-8")
        logger.info("PostMortem: Drafted %s", output_path)
        return output_path

    def _render_report(self, turn: Dict, date_str: str) -> str:
        agent_role = turn.get("agent_role", "Unknown")
        exit_code = turn.get("exit_code", -1)
        summary = turn.get("summary") or "(no summary captured)"
        tokens = turn.get("tokens_consumed") or 0
        start_time = turn.get("start_time")
        end_time = turn.get("end_time")
        turn_id = turn.get("turn_id", "unknown")

        start_str = start_time.isoformat() if start_time else "unknown"
        end_str = end_time.isoformat() if end_time else "unknown"

        return f"""# Post-Mortem: Failed Autonomous Turn — {date_str}

## Summary
| Field | Value |
|-------|-------|
| Turn ID | {turn_id} |
| Agent Role | {agent_role} |
| Exit Code | `{exit_code}` |
| Tokens Consumed | {tokens} |
| Start Time | {start_str} |
| End Time | {end_str} |

## Captured Output / stderr
```
{summary}
```

## Proposed Fix
<!-- TODO: Analyse the captured output above and document the root cause and fix here. -->
- Review the `summary` field for error messages.
- Check the agent logs for the session beginning at `{start_str}`.
- If this is a recurring failure, consider adding a guard in the relevant ghost module.

---
*Generated by PostMortemGenerator (yebyen/mecris#255 / kingdonb/mecris#216)*
"""
